### ISSUE TITLE
Volume adjustment at web-interface

### ISSUE THREAD

**Issue by Baaand** [JHoerbst/InnoTune#3]
I have the problem that i cannot adjust the line-in volume on two of my three inno-amps. It always jumps back to 0. It already worked before

thanks

**Comment by AElmecker** [comment]
Try playing the line-in output on the amp with volume 0. After a few seconds you can pause the playback and the volume control should be at volume 10. 
Now you should be able to adjust the volume again.

**Comment by Baaand** [comment]
perfect, thank you!!! :)
